root = "."
tmp_dir = "tmp"
[build]
  cmd = "templ generate && go build -o ./tmp/main ."
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "node_modules"]
  exclude_file = []
  exclude_regex = ["_test.go", "_templ.go$"]
  exclude_unchanged = false
  follow_symlink = false
  include_dir = []
  include_ext = ["go", "templ"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[proxy]
  enabled = true
  app_port = 3000
  proxy_port = 8080

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true