name: Create and Push Docker Image

on:
  push: 
    branches: [ "main" ]

jobs:
  compile-tailwind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install Tailwind CSS CLI
        run: bun install @tailwindcss/cli

      - name: Compile Tailwind CSS
        run: bunx @tailwindcss/cli -i ./static/css/input.css -o ./static/css/output.css --minify
        
      - name: Upload CSS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: css-build
          path: static/css/output.css
  
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    needs: [compile-tailwind]
    steps:
      - uses: actions/checkout@v4
      
      - name: Download CSS artifacts
        uses: actions/download-artifact@v4
        with:
          name: css-build
          path: static/css/

      - name: Get short SHA
        id: short-sha
        run: echo "sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/gotth-stack:latest
            ghcr.io/${{ github.repository_owner }}/gotth-stack:${{ steps.short-sha.outputs.sha }}
    