name: Build and Push Release Docker Image

on:
  release:
    types: [published]

jobs:
  compile-tailwind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install Tailwind CSS CLI
        run: bun install @tailwindcss/cli

      - name: Compile Tailwind CSS
        run: bunx @tailwindcss/cli -i ./static/css/input.css -o ./static/css/output.css --minify
        
      - name: Upload CSS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: css-build
          path: static/css/output.css

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: [compile-tailwind]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Download CSS artifacts
        uses: actions/download-artifact@v4
        with:
          name: css-build
          path: static/css/
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/gotth-stack
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}